---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: greeting-app
  name: greeting-app
---
apiVersion: v1
kind: Service
metadata:
  name: docker-greeting-app
  namespace: greeting-app
spec:
  ports:
  - port: 80
    targetPort: node-port
    protocol: TCP
  selector:
    app: docker-greeting-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-greeting-app
  namespace: greeting-app
  labels:
    app: docker-greeting-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.spring-web-app: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker-greeting-app
  template:
    metadata:
      labels:
        app: docker-greeting-app
    spec:
      containers:
      - name: greeting-service
        image: arcticgreetings/greeting-service:1.0.0
        ports:
        - name: node-port
          containerPort: 8080
